export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FILTER_PATIENT_BY_STATUS = "FILTER_PATIENT_BY_STATUS"
export const FILTER_PATIENT_BY_ID = "FILTER_PATIENT_BY_ID"
export const ADD_PATIENT = 'ADD_PATIENT';
export const FILTER_PATIENT = "FILTER_PATIENT";

export const FILTER_EMPLOYEE = "FILTER_EMPLOYEE";
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';

export const FETCH_RESULT = 'FETCH_REPORT';
export const ADD_RESULT = 'ADD_REPORT';
export const FILTER_RESULT_BY_DOCTOR = 'FILTER_RESULT_BY_DOCTOR';
export const FILTER_RESULT_BY_DOCTOR_APPO = 'FILTER_RESULT_BY_DOCTOR_APPO';
export const FILTER_RESULT_BY_PATIENT = 'FILTER_RESULT_BY_PATIENT'

export const FETCH_USER = 'FETCH_USER';
export const USERS = "USERS";
export const FILTER_USER_BY_STATUS = 'FILTER_PATIENT_BY_STATUS';
export const FILTER_RESULT_UPDATED ='FILTER_RESULT_UPDATED';
export const FILTER_RESULT_BY_DOCTOR_APPO_FOR_PATIENT = 'FILTER_RESULT_BY_DOCTOR_APPO_FOR_PATIENT';
